version: "3"
services:
  vernemq:
    image: vernemq/vernemq
    ports:
      - 1883:1883
    networks:
      - bridge_networks_1
    volumes:
      - /home/guimog/.asdf/installs/elixir/1.13.0:/opt/elixir
      - ./vmq_elixir_plugin/_build/dev:/opt/vmq_elixir_plugin
    environment:
      - DOCKER_VERNEMQ_LOG__CONSOLE=both
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=3,4,5
networks:
  bridge_networks_1:
    driver: bridge
